name: Java build and docker push
run-name: ${{ github.actor }} Java 🚀
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11' # Set yours java version
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn install
      # set yours docker tag
  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: docker login, build, push
        run: |
          docker login  -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }} ${{ secrets.REGISTRY_HOST }}
          docker build . -t ${{ secrets.REGISTRY_HOST }}/12313210313210321032/${{ github.event.repository.name }}:${GITHUB_RUN_NUMBER}
          docker push ${{ secrets.REGISTRY_HOST }}/12313210313210321032/${{ github.event.repository.name }}:${GITHUB_RUN_NUMBER}